[book]
language = "es"
multilingual = false
title = "Desarrollo de aplicaciones y servicios"
description = "Ejercicios y prácticas"
authors = ["Alberto Peraleda, Álvaro Ruiz"]

[output.html]
additional-js = ["theme/theme.js"]
additional-css = ["theme/theme.css"]
no-section-label = true
git-repository-url = "https://github.com/das/ejercicios"
edit-url-template = "https://github.com/das/ejercicios/edit/main/{path}"

[output.html.print]
enable = false